#ifndef _GUICORE_ENUMS_BRUSHSTYLE_HPP
#define _GUICORE_ENUMS_BRUSHSTYLE_HPP

enum eBrushStyle
{
	TRANSPARENT_BRUSH_STYLE,
	SOLID_BRUSH_STYLE,
	BDIAGONAL_HATCH_BRUSH_STYLE,
	CROSSDIAG_HATCH_BRUSH_STYLE,
	FDIAGONAL_HATCH_BRUSH_STYLE,
	CROSS_HATCH_BRUSH_STYLE,
	HORIZONTAL_HATCH_BRUSH_STYLE,
	VERTICAL_HATCH_BRUSH_STYLE,
	STIPPLE_BRUSH_STYLE,
	STIPPLE_MASK_OPAQUE_BRUSH_STYLE,

	MAX_BRUSH_STYLES
};

#endif // _GUICORE_ENUMS_BRUSHSTYLE_HPP