#ifndef _GUICORE_ENUMS_BUTTONANIMATIONPHASE_HPP
#define _GUICORE_ENUMS_BUTTONANIMATIONPHASE_HPP

enum eButtonAnimationPhase
{
	DISABLED_BUTTON_PHASE,
	NORMAL_BUTTON_PHASE,
	PRESSED_BUTTON_PHASE,
	HIGHLIGHT_BUTTON_PHASE,
	PRESSED_HIGHLIGHTED_BUTTON_PHASE, // primarily for static buttons

	MAX_BUTTON_ANIMATION_PHASES
};

#endif // _GUICORE_ENUMS_BUTTONANIMATIONPHASE_HPP