#ifndef _GUICORE_ENUMS_PENSTYLE_HPP
#define _GUICORE_ENUMS_PENSTYLE_HPP

enum ePenStyle
{
	TRANSPARENT_PEN_STYLE,
	SOLID_PEN_STYLE,
	DOT_PEN_STYLE,
	LONG_DASH_PEN_STYLE,
	SHORT_DASH_PEN_STYLE,
	DOT_DASH_PEN_STYLE,
	MAX_PEN_STYLE
};

#endif // _GUICORE_ENUMS_PENSTYLE_HPP