#ifndef _CORE_ENUMS_UNITMOVEMENTTYPE_HPP
#define _CORE_ENUMS_UNITMOVEMENTTYPE_HPP

enum eUnitMovementType
{
	NO_MOVEMENT_TYPE,

	GROUND_MOVEMENT_TYPE,
	FLYING_MOVEMENT_TYPE,

	MOVEMENT_TYPE_TYPES
};

#endif // _CORE_ENUMS_UNITMOVEMENTTYPE_HPP