#ifndef _GUI_ENUMS_GROUPTYPE_HPP
#define _GUI_ENUMS_GROUPTYPE_HPP

enum eGroupType
{
	CUSTOM_GROUP,
	ONE_COLOUMN_GROUP,
	TWO_COLOUMNS_GROUP,
	HORIZONTAL_GROUP,
	TWO_LINES_GROUP
};

#endif // _GUI_ENUMS_GROUPTYPE_HPP