#ifndef _SDL_ENUMS_AUTOSIZE_HPP
#define _SDL_ENUMS_AUTOSIZE_HPP

enum eAutoSize
{
	NOTHING,
	NO_AUTO_SIZE,
	AUTO_SIZE,
	AUTO_HEIGHT_FULL_WIDTH,
	AUTO_DOUBLE_HEIGHT_FULL_WIDTH,
	FULL_WIDTH,
	AUTO_HEIGHT_CONST_WIDTH,
	AUTO_DOUBLE_HEIGHT_CONST_WIDTH,
	CONST_SIZE //~~ constant width
};

#endif // _SDL_ENUMS_AUTOSIZE_HPP
