#ifndef _SDL_ENUMS_FRAMETICKS_HPP
#define _SDL_ENUMS_FRAMETICKS_HPP

enum eFrameTicks
{
	DRAW_TICKS,
	GENERATION_TICKS,
	PROCESS_TICKS,
	MESSAGE_TICKS,
	SOUND_TICKS,
	IDLE_TICKS,
	
	MAX_TICK_TYPES
};

#endif // _SDL_ENUMS_FRAMETICKS_HPP