#ifndef _GAMES_ENUMS_BROODWARRACES_HPP
#define _GAMES_ENUMS_BROODWARRACES_HPP

enum eBroodWarRaces
{
	NEUTRAL_RACE,
	TERRA_RACE,
	PROTOSS_RACE,
	ZERG_RACE,

	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_BROODWARRACES_HPP