#ifndef _GAMES_ENUMS_STARCRAFT2RACES_HPP
#define _GAMES_ENUMS_STARCRAFT2RACES_HPP

enum eStarCraft2Races
{
	NEUTRAL_RACE,
	TERRA_RACE,
	PROTOSS_RACE,
	ZERG_RACE,

	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_STARCRAFT2RACES_HPP