#ifndef _GAMES_ENUMS_STARCRAFTRACES_HPP
#define _GAMES_ENUMS_STARCRAFTRACES_HPP

enum eStarCraftRaces
{
	NEUTRAL_RACE,
	TERRA_RACE,
	PROTOSS_RACE,
	ZERG_RACE,

	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_STARCRAFTRACES_HPP