#ifndef _GAMES_ENUMS_WARCRAFT2_RACES_HPP
#define _GAMES_ENUMS_WARCRAFT2_RACES_HPP

enum eWarCraft2Races
{
	NEUTRAL_RACE,
	HUMAN_RACE,
	ORC_RACE,
	
	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_WARCRAFT2_RACES_HPP