#ifndef _GAMES_ENUMS_WARCRAFT3RACES_HPP
#define _GAMES_ENUMS_WARCRAFT3RACES_HPP

enum eWarCraft3Races
{
	NEUTRAL_RACE,
	HUMAN_RACE,
	ORC_RACE,
	NIGHTELF_RACE,
	UNDEAD_RACE,

	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_WARCRAFT3RACES_HPP