#ifndef _GAMES_ENUMS_WARCRAFT3_TFTRACES_HPP
#define _GAMES_ENUMS_WARCRAFT3_TFTRACES_HPP

enum eWarCraft3TFTRaces
{
	NEUTRAL_RACE,
	HUMAN_RACE,
	ORC_RACE,
	NIGHTELF_RACE,
	UNDEAD_RACE,

	MAX_RACE_NUM
};

#endif // _GAMES_ENUMS_WARCRAFT3_TFTRACES_HPP