#ifndef _GEOMETRY_ENUMS_DOCKTYPE_HPP
#define _GEOMETRY_ENUMS_DOCKTYPE_HPP

enum eDockType
{
	NO_DOCKTYPE,

	ABSOLUTE_COORDINATE_DOCKTYPE,

	DOCK_WITH_BEGINNING_BORDER_OF_DOCKTYPE,
	DOCK_WITH_ENDING_BORDER_OF_DOCKTYPE,
	DOCK_WITH_BEGINNING_INSIDE_OF_DOCKTYPE,
	DOCK_WITH_ENDING_INSIDE_OF_DOCKTYPE,
	DOCK_WITH_CENTER_INSIDE_OF_DOCKTYPE,

	MAX_DOCKTYPES
};

#endif // _GEOMETRY_ENUMS_DOCKTYPE_HPP

