#ifndef _GEOMETRY_ENUMS_POSITIONMODE_HPP
#define _GEOMETRY_ENUMS_POSITIONMODE_HPP

enum ePositionMode
{
	DO_NOT_ADJUST,
	TOTAL_CENTERED,
	HORIZONTALLY_CENTERED,
	VERTICALLY_CENTERED,
	TOP_LEFT,
	TOP_CENTER,
	TOP_RIGHT,
	CENTER_RIGHT,
	BOTTOM_RIGHT,
	BOTTOM_CENTER,
	BOTTOM_LEFT,
	CENTER_LEFT,
	SPECIAL_BUTTON_LEFT // normal button but put text left
};

#endif // _GEOMETRY_ENUMS_POSITIONMODE_HPP