#ifndef _GEOMETRY_ENUMS_TOUCHTYPE_HPP
#define _GEOMETRY_ENUMS_TOUCHTYPE_HPP

enum eTouchType 
{
	TOUCHES_NO_TOUCH,
	TOUCHES_IS_COMPLETELY_INSIDE,
	TOUCHES_CROSSES_RIGHT_BORDER,
	TOUCHES_CROSSES_LOWER_BORDER,
	TOUCHES_CROSSES_LEFT_BORDER,
	TOUCHES_CROSSES_UPPER_BORDER,
	TOUCHES_CROSSES_BOTTOM_RIGHT_CORNER,
	TOUCHES_CROSSES_BOTTOM_LEFT_CORNER,
	TOUCHES_CROSSES_TOP_LEFT_CORNER,
	TOUCHES_CROSSES_TOP_RIGHT_CORNER,
	TOUCHES_CROSSES_LEFT_AND_RIGHT_BORDER,
	TOUCHES_CROSSES_TOP_AND_BOTTOM_BORDER,
	TOUCHES_CROSSES_UPPER_AREA,
	TOUCHES_CROSSES_RIGHT_AREA,
	TOUCHES_CROSSES_LOWER_AREA,
	TOUCHES_CROSSES_LEFT_AREA,

	TOUCHES_RIGHT_BORDER,
	TOUCHES_LOWER_BORDER,
	TOUCHES_LEFT_BORDER,
	TOUCHES_UPPER_BORDER
};

#endif // _GEOMETRY_ENUMS_TOUCHTYPE_HPP